//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KazumiAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cliente()
        {
            this.documento = new HashSet<documento>();
        }
    
        public int id_cliente { get; set; }
        public int id_tipo_cliente { get; set; }
        public string letra_rif { get; set; }
        public string numero_rif { get; set; }
        public string digito_rif { get; set; }
        public string nombre_razon { get; set; }
        public string domicilio_fiscal { get; set; }
        public string registro_mercantil { get; set; }
        public string ubicacion { get; set; }
        public string telefono { get; set; }
        public string correo_e { get; set; }
    
        public virtual tipo_cliente tipo_cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<documento> documento { get; set; }
    }
}
