//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KazumiAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class documento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public documento()
        {
            this.documento_producto = new HashSet<documento_producto>();
        }
    
        public int id_documento { get; set; }
        public Nullable<int> relacionado_documento { get; set; }
        public string numero_documento { get; set; }
        public Nullable<int> id_empleado { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public System.DateTime fecha_documento { get; set; }
        public Nullable<System.DateTime> fecha_entrega { get; set; }
        public double base_imponible { get; set; }
        public Nullable<double> alicuota_iva { get; set; }
        public string codigo_tipo_documento { get; set; }
    
        public virtual cliente cliente { private get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<documento_producto> documento_producto { private get; set; }
        public virtual tipo_documento tipo_documento { private get; set; }
        public virtual empleado empleado { get; set; }
    }
}
